development:
  solr_home:        <%= ENV['SOLR_HOME']      || "/quod-dev/idx/h/hydra-solr" %>
  solr_admin_url:   <%= ENV['SOLR_ADMIN_URL'] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/admin" %>
  solr_core_name:   umrdr
  solr_core_parent: ''
  fedora_url:       localhost:8080/fedora/rest

testing:
  solr_home:        <%= ENV['SOLR_HOME']      || "/quod-dev/idx/h/hydra-solr" %>
  solr_admin_url:   <%= ENV['SOLR_ADMIN_URL'] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/admin" %>
  solr_core_name:   umrdr
  solr_core_parent: ''
  fedora_url:       localhost:8080/fedora/rest
